name: Deploy on Azure
on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install azd
        uses: Azure/setup-azd@v1.0.0

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Log in with Azure (Federated Credentials)
        if: ${{ secrets.AZURE_CLIENT_ID != '' }}
        run: |
          azd auth login \
            --client-id "${{ secrets.AZURE_CLIENT_ID }}" \
            --federated-credential-provider "github" \
            --tenant-id "${{ secrets.AZURE_TENANT_ID }}"
        shell: bash

      - name: Log in with Azure (Client Credentials)
        if: ${{ secrets.AZURE_CREDENTIALS != '' }}
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -r '.clientSecret' | xargs -I {} echo "::add-mask::{}"
          azd auth login \
            --client-id "$(echo ${{ secrets.AZURE_CREDENTIALS }} | jq -r '.clientId')" \
            --client-secret "$(echo ${{ secrets.AZURE_CREDENTIALS }} | jq -r '.clientSecret')" \
            --tenant-id "$(echo ${{ secrets.AZURE_CREDENTIALS }} | jq -r '.tenantId')"
        shell: bash

      # Remove WEBSITE_RUN_FROM_PACKAGE setting after successful login
      - name: Remove WEBSITE_RUN_FROM_PACKAGE setting
        run: az functionapp config appsettings delete --name func-api-cz3xpwa236bls --resource-group rg-chatyatri-rg --setting-name WEBSITE_RUN_FROM_PACKAGE

      - name: Provision and deploy application
        run: azd up --no-prompt
        env:
          AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
