name: Deploy on Azure
on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}  # Use the secret stored in GitHub Secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install azd
        uses: Azure/setup-azd@v1.0.0

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Log in with Azure (Client Credentials)
        run: |
          # Use the AZURE_CREDENTIALS secret directly without writing to a file
          clientId=$(echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -r .clientId)
          clientSecret=$(echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -r .clientSecret)
          tenantId=$(echo "${{ secrets.AZURE_CREDENTIALS }}" | jq -r .tenantId)
          
          # Perform login using these values
          az login --service-principal --username "$clientId" --password "$clientSecret" --tenant "$tenantId"
        shell: bash

      - name: Remove WEBSITE_RUN_FROM_PACKAGE setting
        run: az functionapp config appsettings delete --name func-api-cz3xpwa236bls --resource-group rg-chatyatri-rg --setting-name WEBSITE_RUN_FROM_PACKAGE

      - name: Provision and deploy application
        run: azd up --no-prompt
        env:
          AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
