name: Deploy on Azure
on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install azd
        uses: Azure/setup-azd@v1.0.0

      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Log in with Azure (Client Credentials)
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > "$GITHUB_WORKSPACE/azure_credentials.json"
          az login --service-principal `
            --username "$(jq -r .clientId $GITHUB_WORKSPACE/azure_credentials.json)" `
            --password "$(jq -r .clientSecret $GITHUB_WORKSPACE/azure_credentials.json)" `
            --tenant "$(jq -r .tenantId $GITHUB_WORKSPACE/azure_credentials.json)"
        shell: pwsh

      - name: Remove WEBSITE_RUN_FROM_PACKAGE setting
        run: az functionapp config appsettings delete --name func-api-cz3xpwa236bls --resource-group rg-chatyatri-rg --setting-name WEBSITE_RUN_FROM_PACKAGE

      - name: Provision and deploy application
        run: azd up --no-prompt
        env:
          AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
