@YatharthChauhan2362 ➜ /workspaces/serverless-chatbot-azure (main) $ azd up

Packaging services (azd package)

  (✓) Done: Packaging service api
  - Package Output: /tmp/serverless-chat-langchainjs-api-azddeploy-1731401356.zip

  (✓) Done: Packaging service webapp
  - Package Output: dist

Provisioning Azure resources (azd provision)
Provisioning Azure resources can take some time.

Subscription: Yatharth Chauhan - Enterprise Subscription (a7753200-3f73-4788-8640-7798e592cc84)
Location: East US 2

  (-) Skipped: Didn't find new changes.

Deploying services (azd deploy)

  (✓) Done: Deploying service api
  - Endpoint: https://func-api-cz3xpwa236bls.azurewebsites.net/

  (✓) Done: Deploying service webapp
  - Endpoint: https://gentle-pebble-0d517420f.5.azurestaticapps.net/


SUCCESS: Your up workflow to provision and deploy to Azure completed in 4 minutes 32 seconds.
@YatharthChauhan2362 ➜ /workspaces/serverless-chatbot-azure (main) $ 
