name: Deploy to Azure with Azure Developer CLI

on:
  push:
    branches:
      - main  # Triggers the workflow on push events to the main branch.
  workflow_dispatch:  # Allows you to manually trigger the workflow from GitHub UI.

jobs:
  deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment.
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.

      - name: Set up Azure CLI
        uses: azure/setup-azcli@v1  # Setup Azure CLI for use in the subsequent steps.

      - name: Azure CLI Login and azd Operation
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} -t ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azd up --environment deployment-env-1 --no-prompt
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
