name: Deploy on Azure

on:
  push:
    branches:
      - main  # Trigger on commits to the main branch
  workflow_dispatch:  # Allow manual triggers from the GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest  # Using the latest Ubuntu runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository to the GitHub Actions runner

      - name: Set up Azure CLI
        uses: azure/setup-azcli@v1  # Setup Azure CLI for use in subsequent steps

      - name: Log in to Azure
        uses: azure/login@v2  # Perform Azure login using service principal credentials
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"  # Optional: specify if required
            }

      - name: Install Azure Developer CLI
        run: npm install -g azure-dev@latest  # Install the latest Azure Developer CLI for deployment

      - name: Deploy using Azure Developer CLI
        run: azd up --no-prompt  # Deploy to Azure using 'azd up', ensures that interaction is non-blocking
        env:
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  # Use Azure subscription ID from secrets

      - name: Print deployment endpoint
        run: echo "Deployment successful"  # Placeholder; replace with actual command to fetch or display deployment endpoint if necessary

      - name: Logout from Azure
        if: always()  # This step will run regardless
