name: Deploy on Azure
on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Corrected to a valid version if v4 doesn't exist yet

      - name: Set up Azure CLI
        uses: azure/setup-azcli@v1  # Assuming you need Azure CLI, change if setup-azd was actually required

      - name: Set up Nodejs
        uses: actions/setup-node@v3  # Corrected to the latest existing version
        with:
          node-version: '20.x'  # Ensuring proper format for node version

      - name: Log in with Azure
        uses: azure/login@v1  # Replacing with correct azure login if necessary
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Remove WEBSITE_RUN_FROM_PACKAGE setting  # Ensured this runs after successfully logging in
        run: |
          az functionapp config appsettings delete --name func-api-cz3xpwa236bls --resource-group rg-chatyatri-rg --setting-name WEBSITE_RUN_FROM_PACKAGE

      - name: Provision and deploy application  # Ensuring Azure deployment command is correctly formatted, adjust if actual azd up is different
        run: |
          azd up --no-prompt
        env:
          AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
