name: Deploy to Azure

on:
  workflow_dispatch:   # Allows manual trigger of the workflow
  push:
    branches: [main]   # Runs on push to main branch, adjust as needed

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: "prod"  # Change this to your environment name if different
      AZURE_LOCATION: "eastus"  # Set your Azure region

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Azure Developer CLI (azd)
        uses: Azure/setup-azd@v1
        with:
          version: "latest"

      - name: Log in to Azure
        run: |
          az login --service-principal \
            --username $AZURE_CLIENT_ID \
            --password $AZURE_CLIENT_SECRET \
            --tenant $AZURE_TENANT_ID
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Set subscription
        run: az account set --subscription $AZURE_SUBSCRIPTION_ID

      - name: Deploy application using azd
        run: azd up --no-prompt
        env:
          AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ env.AZURE_LOCATION }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
