name: Azure App Deployment

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AZD_ENVIRONMENT_NAME: deployment-env-1  # Example environment name, change as needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Install Azure Developer CLI (azd)
      run: |
        curl -fsSL https://aka.ms/install-azd.sh | bash

    - name: Deploy with azd up
      run: azd up --environment ${{ env.AZD_ENVIRONMENT_NAME }} --no-prompt
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
